name: Meu Workflow

on:
  workflow_dispatch:
    inputs:
      old_text:
        description: "Texto a ser adicionado ao README"
        required: true
      new_text:
        description: "Texto a ser substituído no README"
        required: true

permissions:
  contents: write

jobs:
  read-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read README
      run: |
        echo "README.md:"
        cat README.md

  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update README
      run: |
        sed -i "s/${{ inputs.new_text }}/${{ inputs.old_text }}/g" README.md
    
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update README with input text"
        git push