name: Update README

workflow_dispatch:
  inputs:
    text:
      description: "Texto a ser adicionado ao README"
      required: true

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add text to README
      run: echo "${{ inputs.text }}" >> README.md
